/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public static void problemI() {
/**  Strategy 1
 *  @data store data in memory with this position.
 */
    int[] data = new Producer().produceInMemory();
    new MTWriter().writeFromMemory(4, data);

/**  Strategy 2
 *  @output store data in disk with "data_generation.txt".
 */
    String output = new Producer().produceInDisk();
    new MTWriter().writeFromDisk(4);

/**  Strategy 3
 *  multi-thread produce and write.
 */
    new MTWriter().produceWhileWrite(4);
  }

  public static void problemII() {
/**  Strategy 1
 *
 */
    int[] data = new Producer().produceInMemory();
    new HDWriter().writeFromMemory(4, data);

/**  Strategy 2
 *
 */
    new HDWriter().writeFromDisk(4);
  }

  public static void problemIII() {
/**  Strategy 1
 *
 */
    int[] data = new Producer().produceInMemory();
    new CAWriter().writeFromMemry(4, data);

/**  Strategy 2
 *
 */

  }

  public static void main(String[] args) {
    problemI();
    problemII();
//    problemIII();
  }
}
