/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  public static void problemI() {
/**  Strategy 1
 *  @data store data in memory with this position.
 */
    int[] data = new Producer().produceInMemory();
    new MTWriter().writeFromMemory(5, data);

/**  Strategy 2
 *  @output store data in disk with "data_generation.txt".
 */
    String output = new Producer().produceInDisk();
    new MTWriter().writeFromDisk(5);

/**  Strategy 3
 *  multi-thread produce and write.
 */
    new MTWriter().produceWhileWrite(5);
  }

  public static void problemII() {

  }

  public static void problemIII() {

  }

  public static void main(String[] args) {
    problemI();
    problemII();
    problemIII();
  }
}
